words = [
    "allauth",
    "beszel",
    "bindkey",
    "bitdepth",
    "bitwarden",
    "borgbackup",
    "catppuccin",
    "dbhost",
    "esac",
    "fetchurl",
    "highres",
    "hyprctl",
    "ipc",
    "ldaps",
    "pkgs",
    "rawio",
    "repokey",
    "smartmontools",
    "smoothbrained",
    "socialaccount",
    "suidsgid",
    "sysaccounts",
    "tika",
    "tmout",
    "tty",
    "xdg",
]
