#! /usr/bin/env bash

cd ~/gitlab.codethink/codethings/kiranostrolenk/nixos-config
git update-index --refresh
if ! git diff-index --quiet HEAD --
then
	[ -z "$@" ] && exit 1
	read com_message
	git commit "$@" -m "$com_message"
fi
datey=$(date +%d_%m_%y)
branch=$(git branch --show-current)
message=$(git log -1 --pretty=%B | head -1 | sed 's/ /_/g')

profile_name="$branch $message $datey"

if echo "$profile_name" | rg '/'
then
    echo 'No / you fool'
fi

sudo nixos-rebuild switch -p "$profile_name"
