#! /usr/bin/env bash

cd ~/gitlab.codethink/codethings/kiranostrolenk/nixos-config
git update-index --refresh
if ! git diff-index --quiet HEAD --
then
	[ -z "$@" ] && exit 1
	git diff
	read com_message
	git commit "$@" -m "$com_message"
fi
datey=$(date +%y-%m-%d_%H-%M)
message=$(git log -1 --pretty=%B | head -1 | sed 's/ /_/g')

profile_name="${datey}_${message}"

echo "profile name: $profile_name"
read -p "Ok?" -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

if echo "$profile_name" | rg '/'
then
    echo 'No / you fool'
fi

sudo nixos-rebuild switch -p "$profile_name"
