#! /usr/bin/env bash

git update-index --refresh
if ! git diff-index --quiet HEAD --
then
	git diff
	exit 1
fi
datey=$(date +%y-%m-%d_%H-%M)
message=$(git log -1 --pretty=%B | head -1 | sed 's/ /_/g' | sed 's/://')

profile_name="${datey}_${message}"

echo "profile name: $profile_name"
echo    # (optional) move to a new line

if echo "$profile_name" | rg "[/':,]"
then
    echo 'No / you fool'
    exit 1
fi

update-nix-fetchgit system-config/pkgs_mine/colorful_loop/default.nix&
sudo nixos-rebuild --flake .#$1 switch --impure -p "$profile_name" "${@:2}"
